"""empty message

Revision ID: 20f14f1aa6ea
Revises: dbec8a08a0cf
Create Date: 2023-09-13 20:56:50.149820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f14f1aa6ea'
down_revision = 'dbec8a08a0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bicycle_review', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'bicycles', ['bicycle_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bicycle_review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
