"""empty message

Revision ID: 525fb1539a02
Revises: 1b15b0f0363c
Create Date: 2023-10-30 20:06:06.197428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525fb1539a02'
down_revision = '1b15b0f0363c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('price_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('price_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
