"""empty message

Revision ID: 79a13cbb25d7
Revises: eac43a99a72f
Create Date: 2023-10-01 15:08:24.847350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a13cbb25d7'
down_revision = 'eac43a99a72f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bicycles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bicycles', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
