"""empty message

Revision ID: 96e2742c06c9
Revises: d2dcd8dfb7e6
Create Date: 2023-09-17 14:46:27.670080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96e2742c06c9'
down_revision = 'd2dcd8dfb7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ShippingAddress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ShippingAddress', schema=None) as batch_op:
        batch_op.drop_column('city')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
